import type { Challenge } from "./tutor-contracts";

const hints = (a: string, b: string, c: string): Challenge["hints"] => [
  { level: 1, text: a },
  { level: 2, text: b },
  { level: 3, text: c },
];

export const heartChallenges: Challenge[] = [
  { id: "heart-identify-lv", sceneId: "cardiac", type: "identify", prompt: "Select the chamber that pumps blood into the systemic circuit.", concepts: ["left-ventricle", "systemic-pump"], targetHotspotIds: ["left-ventricle"], hints: hints("Look for the thickest ventricular wall.", "It sits on the anatomical left side of the heart.", "Select the left ventricle."), difficulty: 1 },
  { id: "heart-identify-rv", sceneId: "cardiac", type: "identify", prompt: "Select the chamber that sends deoxygenated blood toward the lungs.", concepts: ["right-ventricle", "pulmonary-flow"], targetHotspotIds: ["right-ventricle"], hints: hints("This chamber supplies the pulmonary circuit.", "It is thinner-walled than its partner.", "Select the right ventricle."), difficulty: 1 },
  { id: "heart-identify-la", sceneId: "cardiac", type: "identify", prompt: "Select the chamber that receives oxygenated blood returning from the lungs.", concepts: ["left-atrium", "oxygenated-return"], targetHotspotIds: ["left-atrium"], hints: hints("Start with the receiving chambers.", "Blood then crosses the mitral valve.", "Select the left atrium."), difficulty: 1 },
  { id: "heart-identify-ra", sceneId: "cardiac", type: "identify", prompt: "Select the chamber that receives systemic venous return.", concepts: ["right-atrium", "venous-return"], targetHotspotIds: ["right-atrium"], hints: hints("The venae cavae empty here.", "It contains the sinoatrial node.", "Select the right atrium."), difficulty: 1 },
  { id: "heart-identify-aorta", sceneId: "cardiac", type: "identify", prompt: "Select the great vessel that carries oxygenated blood to the systemic circulation.", concepts: ["aorta", "systemic-flow"], targetHotspotIds: ["aorta"], hints: hints("It leaves the high-pressure ventricle.", "It forms a prominent arch.", "Select the aorta."), difficulty: 1 },
  { id: "heart-identify-pulmonary", sceneId: "cardiac", type: "identify", prompt: "Select the artery that carries deoxygenated blood toward the lungs.", concepts: ["pulmonary-artery", "pulmonary-flow"], targetHotspotIds: ["pulmonary-artery"], hints: hints("Artery describes direction, not oxygen content.", "It leaves the right ventricle.", "Select the pulmonary trunk."), difficulty: 1 },
  { id: "heart-identify-mitral", sceneId: "cardiac", type: "identify", prompt: "Select the valve between the left atrium and left ventricle.", concepts: ["mitral-valve", "left-heart-flow"], targetHotspotIds: ["mitral-valve"], hints: hints("It is an atrioventricular valve.", "It has two leaflets.", "Select the mitral valve."), difficulty: 1 },
  { id: "heart-identify-aortic-valve", sceneId: "cardiac", type: "identify", prompt: "Select the valve between the left ventricle and aorta.", concepts: ["aortic-valve", "left-heart-flow"], targetHotspotIds: ["aortic-valve"], hints: hints("It is a semilunar valve.", "It guards the systemic outflow tract.", "Select the aortic valve."), difficulty: 1 },
  { id: "heart-trace-oxygenated", sceneId: "cardiac", type: "trace", prompt: "Trace oxygenated blood through the visible left-heart structures, from its receiving chamber to the systemic artery.", concepts: ["left-heart-flow", "flow-ordering", "oxygenated-blood"], expectedSequence: ["left-atrium", "mitral-valve", "left-ventricle", "aortic-valve", "aorta"], hints: hints("Begin where blood returns from the lungs.", "Include both the inlet and outflow valves around the ventricle.", "Left atrium → mitral valve → left ventricle → aortic valve → aorta."), difficulty: 2 },
  { id: "heart-trace-pressure", sceneId: "cardiac", type: "trace", prompt: "Trace the structures that progressively generate and deliver systemic pressure.", concepts: ["left-heart-flow", "pressure-generation"], expectedSequence: ["left-atrium", "mitral-valve", "left-ventricle", "aortic-valve", "aorta"], hints: hints("Start before the main pressure-generating chamber.", "Include the semilunar valve after the ventricle.", "Left atrium → mitral valve → left ventricle → aortic valve → aorta."), difficulty: 3 },
  { id: "heart-compare-ventricles", sceneId: "cardiac", type: "compare", prompt: "Select both ventricles to compare their wall thickness and workload.", concepts: ["ventricular-comparison", "pressure-generation"], targetHotspotIds: ["left-ventricle", "right-ventricle"], hints: hints("Choose the two lower pumping chambers.", "One supplies the lungs and one supplies the body.", "Select both the left and right ventricles."), difficulty: 1 },
  { id: "heart-compare-great-vessels", sceneId: "cardiac", type: "compare", prompt: "Select the two visible great arteries to compare pulmonary and systemic circulation.", concepts: ["great-vessels", "circulation-comparison"], targetHotspotIds: ["aorta", "pulmonary-artery"], hints: hints("Both vessels carry blood away from a ventricle.", "One goes to the lungs; one goes to the body.", "Select the pulmonary trunk and aorta."), difficulty: 2 },
  { id: "heart-spatial-mitral", sceneId: "cardiac", type: "spatial_relation", prompt: "Select the structures immediately before and after the mitral valve in blood-flow order.", concepts: ["mitral-valve", "spatial-relation", "flow-ordering"], expectedSequence: ["left-atrium", "left-ventricle"], hints: hints("The valve links an atrium to a ventricle.", "Stay on the left side of the heart.", "Left atrium, then left ventricle."), difficulty: 2 },
  { id: "heart-spatial-outflow", sceneId: "cardiac", type: "spatial_relation", prompt: "Select the chamber, valve and great vessel forming the visible systemic outflow path.", concepts: ["left-ventricle", "aortic-valve", "aorta", "spatial-relation"], expectedSequence: ["left-ventricle", "aortic-valve", "aorta"], hints: hints("Systemic outflow begins in the thick-walled chamber.", "Pass through the semilunar valve before the arching artery.", "Left ventricle → aortic valve → aorta."), difficulty: 2 },
  { id: "heart-function-thick-wall", sceneId: "cardiac", type: "function_reasoning", prompt: "Select the structure whose thick wall is an adaptation for pumping against high systemic resistance.", concepts: ["left-ventricle", "structure-function", "pressure-generation"], targetHotspotIds: ["left-ventricle"], hints: hints("Compare the work of the two circulations.", "The body-wide circuit needs higher pressure.", "Select the left ventricle."), difficulty: 2 },
  { id: "heart-function-low-pressure", sceneId: "cardiac", type: "function_reasoning", prompt: "Select the chamber adapted to the lower-resistance pulmonary circuit.", concepts: ["right-ventricle", "structure-function", "pulmonary-flow"], targetHotspotIds: ["right-ventricle"], hints: hints("Its destination is nearby compared with the systemic circuit.", "Its wall is thinner.", "Select the right ventricle."), difficulty: 2 },
  { id: "heart-function-valve", sceneId: "cardiac", type: "function_reasoning", prompt: "Select the structure that prevents backflow from the left ventricle into the left atrium during systole.", concepts: ["mitral-valve", "valve-function"], targetHotspotIds: ["mitral-valve"], hints: hints("Look for a one-way structure.", "It closes as ventricular pressure rises.", "Select the mitral valve."), difficulty: 2 },
  { id: "heart-function-coronary", sceneId: "cardiac", type: "function_reasoning", prompt: "Select the vessels that supply the myocardium itself.", concepts: ["coronary", "myocardial-perfusion"], targetHotspotIds: ["coronary"], hints: hints("The heart muscle needs its own blood supply.", "These vessels fill most effectively during diastole.", "Select the coronary arteries."), difficulty: 2 },
  { id: "heart-advanced-left-flow", sceneId: "cardiac", type: "trace", prompt: "Without a hint, reconstruct the complete visible route of oxygenated blood through the left side of the heart.", concepts: ["left-heart-flow", "flow-ordering", "oxygenated-blood"], expectedSequence: ["left-atrium", "mitral-valve", "left-ventricle", "aortic-valve", "aorta"], hints: hints("Identify receiving chamber, inlet valve, pump, outflow valve, then artery.", "The bicuspid valve is second and the semilunar valve is fourth.", "Left atrium → mitral valve → left ventricle → aortic valve → aorta."), difficulty: 3 },
];
